In [1]:
with open('Dataset_messege.txt', 'r') as file:
    data = file.read()
print(data)

Hey guys, what's up?
Kuch nahi yrr, just chilling. Tum batao?
I'm gd! Planning kya chal raha hai weekend mein?
Let's go for a movie, koi suggestions?
How about watching the new Marvel movie?
Hnn yrr, wo accha rahega. Kab chalna hai?
Sunday afternoon sound karega?
Perfect! Show timings kya hai?
Main check karta hoon and let u know.
Cool, let's finalize by tomorrow evening.
Ok, sab ready hai movie ke liye?
Haan, I'm excited!
Yay! Mujhe bhi wait nahi ho raha.
Maza aayega guys, group outing baad mein bhi plan karte hain.
Done, sounds like a plan.
Great! Let's enjoy the movie first.
Tickets ka arrangement kisne kiya?
Main dekh lunga, don't worry.
Thanks bhai, tu best hai.
Ab chalo booking confirm karte hain.
Movie ke baad dinner bhi plan karna hai kya?
Haan yaar, bilkul. Suggestions karo.
Italian cuisine try karte hain?
Chalo, bahut din ho gaye Italian khaye hue.
Time pe pahunchna hai, show start hone se pehle.
No worries, main punctual hoon.
That's good to know!
Haha, you guys know me well

# New Section

In [2]:
len(data)

13891

In [3]:
import tensorflow as tf
from tensorflow import keras

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
tokenizer.word_index

{'hai': 1,
 'hain': 2,
 'bhi': 3,
 'ka': 4,
 'kuch': 5,
 'karte': 6,
 'yaar': 7,
 'kya': 8,
 'tha': 9,
 'the': 10,
 'ke': 11,
 'plan': 12,
 'bahut': 13,
 'haan': 14,
 'mein': 15,
 'pe': 16,
 'new': 17,
 'you': 18,
 'woh': 19,
 'bhai': 20,
 'xyz': 21,
 'movie': 22,
 'try': 23,
 'ya': 24,
 'kabhi': 25,
 'kaafi': 26,
 'nahi': 27,
 'kiya': 28,
 'next': 29,
 'your': 30,
 'hey': 31,
 "let's": 32,
 'for': 33,
 'main': 34,
 'ho': 35,
 'karna': 36,
 'time': 37,
 'log': 38,
 'hota': 39,
 'hote': 40,
 'raha': 41,
 'koi': 42,
 'se': 43,
 'to': 44,
 'kar': 45,
 'ne': 46,
 'yaad': 47,
 'latest': 48,
 'kaunsa': 49,
 'chal': 50,
 'weekend': 51,
 'accha': 52,
 'good': 53,
 'ko': 54,
 'have': 55,
 'wahaan': 56,
 "what's": 57,
 'and': 58,
 'toh': 59,
 'it': 60,
 'abhi': 61,
 'uska': 62,
 'true': 63,
 'in': 64,
 'hoon': 65,
 'know': 66,
 'sab': 67,
 'liye': 68,
 'sounds': 69,
 'dekha': 70,
 'book': 71,
 'thi': 72,
 'hi': 73,
 'ki': 74,
 'important': 75,
 'nhi': 76,
 'rha': 77,
 'do': 78,
 'yrr': 79,
 'sho

In [5]:
total_words = len(tokenizer.word_index)
total_words

870

In [6]:
input_sequence = []
for sen in data.split('\n') :
   tokenized_seq = tokenizer.texts_to_sequences([sen])[0]
   #print(tokenized_seq)
   for i in range(1,len(tokenized_seq)) :
     input_sequence.append(tokenized_seq[:i+1])

input_sequence

[[31, 94],
 [31, 94, 57],
 [31, 94, 57, 137],
 [5, 27],
 [5, 27, 79],
 [5, 27, 79, 205],
 [5, 27, 79, 205, 206],
 [5, 27, 79, 205, 206, 207],
 [5, 27, 79, 205, 206, 207, 344],
 [138, 345],
 [138, 345, 346],
 [138, 345, 346, 8],
 [138, 345, 346, 8, 50],
 [138, 345, 346, 8, 50, 41],
 [138, 345, 346, 8, 50, 41, 1],
 [138, 345, 346, 8, 50, 41, 1, 51],
 [138, 345, 346, 8, 50, 41, 1, 51, 15],
 [32, 208],
 [32, 208, 33],
 [32, 208, 33, 95],
 [32, 208, 33, 95, 22],
 [32, 208, 33, 95, 22, 42],
 [32, 208, 33, 95, 22, 42, 209],
 [139, 210],
 [139, 210, 211],
 [139, 210, 211, 10],
 [139, 210, 211, 10, 17],
 [139, 210, 211, 10, 17, 212],
 [139, 210, 211, 10, 17, 212, 22],
 [347, 79],
 [347, 79, 348],
 [347, 79, 348, 52],
 [347, 79, 348, 52, 349],
 [347, 79, 348, 52, 349, 213],
 [347, 79, 348, 52, 349, 213, 350],
 [347, 79, 348, 52, 349, 213, 350, 1],
 [351, 352],
 [351, 352, 353],
 [351, 352, 353, 354],
 [96, 80],
 [96, 80, 355],
 [96, 80, 355, 8],
 [96, 80, 355, 8, 1],
 [34, 97],
 [34, 97, 214],
 

In [7]:
max_len = max(len(seq) for seq in input_sequence)
max_len

12

In [8]:
from keras.utils import pad_sequences
padded_input_sequences = pad_sequences(
    input_sequence ,
    maxlen = max_len ,
    padding = 'pre'
)
padded_input_sequences

array([[  0,   0,   0, ...,   0,  31,  94],
       [  0,   0,   0, ...,  31,  94,  57],
       [  0,   0,   0, ...,  94,  57, 137],
       ...,
       [  0,   0,   0, ...,  23,  28,   1],
       [  0,   0,   0, ...,  28,   1, 136],
       [  0,   0,   0, ...,   1, 136, 239]], dtype=int32)

In [9]:
X = padded_input_sequences[:, :-1]
Y = padded_input_sequences[:,-1]
X

array([[  0,   0,   0, ...,   0,   0,  31],
       [  0,   0,   0, ...,   0,  31,  94],
       [  0,   0,   0, ...,  31,  94,  57],
       ...,
       [  0,   0,   0, ..., 343,  23,  28],
       [  0,   0,   0, ...,  23,  28,   1],
       [  0,   0,   0, ...,  28,   1, 136]], dtype=int32)

In [10]:
Y = keras.utils.to_categorical(
    Y , num_classes = total_words
)
Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
# Model Building
from keras.models import Sequential
from keras.layers import Embedding , LSTM , Dense

model = Sequential()
# 870=total no. of words in vocab
# Now each word was represnted by a vector after ohe , but now using embedding we are making it more dense and will have a size of 100
# So here total weights will be 870 * 100
model.add(Embedding(870,100,input_length=11))
# Only mention no. of nodes in LSTM
model.add(LSTM(100))
# In dense we'll add as many nodes as the no. of words in vocab to get prob of each word
model.add(Dense(870,activation='softmax'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.compile(loss='categorical_crossentropy' , optimizer='adam' , metrics = ['accuracy'])
model.summary()
# Now now basically we have some input sequences and each sequence has some words which are represented by a vector of size 100 after embedding
# Now , in LSTM each input sequence is feeded in time steps i.e its first word's vector will be feede at t=0 n so on
# Now , after the last word feeded from an input seq , we will feed the output to dense layer which will give an output of sie 283 ,
# having prob of all the words and one which has highest prob will be treated as predicted output

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.fit(X,Y,epochs=100)

Epoch 1/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0575 - loss: 6.5995
Epoch 2/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.0768 - loss: 5.9883
Epoch 3/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.0796 - loss: 5.8292
Epoch 4/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.0790 - loss: 5.6713
Epoch 5/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.0844 - loss: 5.4962
Epoch 6/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0905 - loss: 5.4394
Epoch 7/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0912 - loss: 5.3079
Epoch 8/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.1067 - loss: 5.1556
Epoch 9/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1090 - loss: 5.1103
Epoch 10/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1241 - loss: 4.9936
Epoch 11/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.1263 - loss: 4.8453
Epoch 12/100
66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy:

In [14]:
# Predicting
import numpy as np
text = "ghumne"

for i in range(10):
  # tokenize
  tokenized_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_tokenized_text = pad_sequences([tokenized_text], maxlen=11, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_tokenized_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step
ghumne ne
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
ghumne ne bhi
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
ghumne ne bhi kaafi
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
ghumne ne bhi kaafi accha
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
ghumne ne bhi kaafi accha kaam
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
ghumne ne bhi kaafi accha kaam kiya
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
ghumne ne bhi kaafi accha kaam kiya hai
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
ghumne ne bhi kaafi accha kaam kiya hai makers
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
ghumne ne bhi kaafi accha kaam kiya hai makers ne
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
ghumne ne bhi kaafi accha kaam kiya hai makers ne hai
